apiVersion: v1
kind: Service
metadata:
  name: ldzib-simple-app
  labels:
    app: ldzib-simple-app
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: ldzib-simple-app
